- name: Run Scraper
        run: node scraper.js
        # Error aye to ignore karo takay step 3 chale
        continue-on-error: true 

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          # 'debug' folder upload kar do
          path: debug/
