name: Test Scraper
on:
  workflow_dispatch: # Taake aap manual button daba kar check kar sakein

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install puppeteer
      - name: Run Script
        run: node scraper.js
